---
# tasks file for npm
- name: Insall npm
  package:
    pkg=npm
    state=latest
    update_cache=yes

- name: Install dependencies
  npm:
    executable: "{{ item.executable|default(omit) }}"
    global: "{{ item.global|default(false) }}"
    registry: "{{ item.registry|default(omit) }}"
    name: "{{ item.name|default(omit) }}"
    path: "{{ item.path|default(omit) }}"
    version: "{{ item.version|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    production: "{{ item.production|default(omit) }}"
    ignore_scripts: "{{ item.ignore_scripts|default(omit) }}"
  with_items: "{{ npm_packages }}"
